### ISSUE TITLE
pyzmq bad url

### ISSUE THREAD

**Issue by buzacott** [awracms/awra_cms_old#1]
When running the conda environment creation script, the following error occurs:
`CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py34_0.tar.bz2>`

Checking on the conda-forge list this version does not exist. I've replaced it with this one
https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.1-py34_0.tar.bz2 and I was able to set up the environment and install successfully.

**Comment by awracms** [comment]
Thanks for reporting this; the package list has been updated
